### ISSUE TITLE
error=logfmt: unterminated string

### ISSUE THREAD

**Issue by mheffner** [ryansmith3136/l2met#118]
Seeing this a lot in the standard output on the Librato l2met. What does this mean?

**Comment by mheffner** [comment]
Log lines in l2met should be expanded to include: time and file:line location of the log line in the code. Right now you can't tell when or where a particular log lines was emitted.

**Comment by collinvandyck** [comment]
Couple of updates:
1. file and line numbers have been included for all logging statements in the librato/l2met project.
2. the librato l2met will now log log-lines that could not be parsed. many of these are because logplex is truncating log messages > 1K which results in an incorrectly formatted log line and hence the parse failure.

Other failures occur from log messages that are < 1K but are simply cut-off permaturely for some reason. Some  more investigation needs to be done in this regard.

**Comment by bmpandrade** [comment]
Hey guys,

I'm trying to use [heroku-datadog-drain-golang](https://github.com/apiaryio/heroku-datadog-drain-golang) and I got the same error.

Is there any development regarding this issue?

**Comment by josephruscio** [comment]
@bmandrade I think as @ryandotsmith [spelled out here](https://github.com/ryandotsmith/l2met#an-important-update) this project is effectively deprecated. At Librato we've been actively developing and maintaining our hosted implementation of l2met that services all our customers on Heroku, but that's not an OSS project. Happy to help with Heroku monitoring needs there, otherwise best of luck!
